### ISSUE TITLE
Create drop-down menu with next level items when a folder from the Ontology is dropped in the cohort definition panel

### ISSUE THREAD

**Issue by JLRaisaro** [CHUV-DS/glowing-bear-medco-bioref#26]
>These concepts should be set to “any” or “all” by default. The user then only has to drag and drop the analyte (e.g. sodium) from the ontology for an analysis.

=> reuse the drop-down menu that appears when numeric concepts are dragged and dropped from the ontology
=> update the logic for displaying a drop-down menu: yes for numeric, yes for folders, no for categorical 
=> load the children when necessary by first checking if they already exist in the cache of the front-end, otherwise fetch them from the DB using the Ontology API

**Comment by SimonCommits** [comment]
TODO (comment for me) When dropping a new concept in the ontology concept zone when there is already one concept it doesn't change the content of the dropdown list
