### ISSUE TITLE
Display of Swiss BioRef-logo

### ISSUE THREAD

**Issue by Harald-W** [CHUV-DS/glowing-bear-medco-bioref#34]
The **Swiss BioRef-logo** should be displayed with reasonable prominence in the user interface, along with the SPHN-logo, and also on the startup screen.
There is three files attached, Swiss BioRef-logo with and without text, plus SPHN-logo.

**Initial solution:**
- Incorporate the Swiss BioRef-logo (**without text**) in front of "**Swiss BioRef WebClient**" in the top bar of the frontend.
 
- Incorporate the **Swiss BioRef-logo (without text**) and the **SPHN-logo** into the **bottom bar of the frontend**, on right side with some reasonable space  towards edge and in-between the logos. Order: Swiss BioRef-logo to the left, SPHN-logo to the right).
 
- **Logos** in the top and bottom bars **should use the maximum space available**, i.e. the entire height of the bar.
 
- **During** the **loading procedure** on the startup-screen ("_Loading Swiss BioRef Web Client..._"), show the **Swiss BioRef-logo with text** full screen **in the background**, maybe using a moderate alpha-level (transparency) if appropriate.

**Final sizes and positions of the logos need to be discussed.**
___

![Swiss_BioRef_Logo_incl_text_300dpi](https://user-images.githubusercontent.com/48758182/161038773-3e3acdc4-9352-40ce-be7e-2d7ca0bd4ff0.png)
![Swiss_BioRef_Logo_without_text_300dpi](https://user-images.githubusercontent.com/48758182/161038779-3f9bedce-c48c-436c-8d19-4562a050bece.png)
![SPHN-Logo-SIB-Colors](https://user-images.githubusercontent.com/48758182/161038824-b0ded6f2-723c-4d49-bdcf-ddc29b929860.png)

**Comment by nfreundl** [comment]
Initial solutions are implemented

In the loading screen:
![logos_2](https://user-images.githubusercontent.com/32438039/180725371-c2a5ff6e-3fcd-4b14-bcf1-6157a180600a.png)

In the interface:

![logos_1](https://user-images.githubusercontent.com/32438039/180725509-e8f9feb4-6ba4-4833-bf53-fec298d55b72.png)

**Comment by JLRaisaro** [comment]
Harald please provide the new logo

**Comment by Harald-W** [comment]
Thanks for the productive meeting yesterday.
As discussed, please make the following changes:
   
- **Increase the hight of the bottom bar** by **at least 50%** (50-70% should do depending on resolution) to allow logos to be displayed in a reasonable size.
   _Seems the best option due to the poor adaptability of the frontend which prevents placing logos in the upper right with ease._
   _--> Probably no need to increase the font size of "Copyright notice", just keep it vertically centered in the bottom bar. <--_
   
- **Replace** both the **logos of Swiss BioRef and SPHN in the bottom bar with** the **updated versions** provided.
   _Slight modifications have been made to improve their perceptibility when displayed at small display size._
   
- **Move the Swiss BioRef-logo in the top bar** significantly **closer to "Swiss BioRef Web Client"** such that the association with it is clear.
_____________
**Overview:**
![2022-08-17_Logos_in_MedCo-frontend](https://user-images.githubusercontent.com/48758182/185361087-a88ee56f-8bbe-4bab-83c6-6a17999a8c6a.png)
____________
**Updated logo files:**
- SPHN
![SPHN_logo_Github_2022-08-17](https://user-images.githubusercontent.com/48758182/185358867-407d02b6-6639-436f-982d-a1d97a1d86a3.png)
   
- Swiss BioRef
![Swiss_BioRef_Logo_Github_2022-08-17](https://user-images.githubusercontent.com/48758182/185358974-b45bde12-9b9f-48f5-b543-d4653d637393.png)
