### ISSUE TITLE
Print additional info in the pdf export

### ISSUE THREAD

**Issue by WiseIndian** [CHUV-DS/glowing-bear-medco-bioref#4]
print
- [x] time of the export

- [x]  name of the user

- [x] query definition summary (name of the filters on the cohort)

- [x] add copyright notice: https://github.com/CHUV-DS/glowing-bear-medco-bioref/issues/28

**Comment by SimonCommits** [comment]
> if the option “treat groups independently” influences the query in any way, it should
> also be included in the report.

- [x] completed

**Comment by Harald-W** [comment]
compare https://github.com/CHUV-DS/glowing-bear-medco-bioref/issues/28#issuecomment-1060627163:

Copyright notices to be displayed both in the user interface AND on the PDF-report:

We can use short copyright notices at the bottom of the UI (Try out different font sizes - notices need to be clearly legible!):
LOINC ® codes and long common names: © 1995-2022, [Regenstrief Institute, Inc.](https://www.regenstrief.org/) and the [LOINC](http://loinc.org/) Committee
GMDN ® codes, terms, and descriptions: © [GMDN Agency](https://www.gmdnagency.org/) 2005-2022.
GUDI codes: courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/)
ICD-10-GM codes and descriptions: © 2022 [Bundesinstitut für Arzneimittel und Medizinprodukte](https://www.bfarm.de/EN/Code-systems/Classifications/ICD/ICD-10-GM/_node.html)

Extended copyright notices should be used at the bottom of the page of PDF-report:
LOINC: This material contains content from LOINC (http://loinc.org/). LOINC is copyright © 1995-2022, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc.
GMDN: GMDN ® is a registered trademark of The GMDN Agency. All rights reserved. The copyright and database rights in the original GMDN materials are owned by The GMDN Agency Ltd 2005-2022. Used under licence from The GMDN Agency Ltd.
GUDI: Global Unique Device Identification codes from the Global Unique Device Identification Database (GUDID) have been retrieved at the [AccessGUDID-portal](https://accessgudid.nlm.nih.gov/) and are a courtesy of the the [U.S. National Library of Medicine](https://www.nlm.nih.gov/) in collaboration with the [U.S. Food and Drug Administration](https://www.fda.gov/).
ICD-10-GM: © 2022 German Federal Institute for Drugs and Medical Devices (Bundesinstitut für Arzneimittel und Medizinprodukte [BfArM](https://www.bfarm.de/EN/Home/_node.html)) on behalf of the German Federal Ministry of Health (Bundesministerium für Gesundheit [BMG](https://www.bundesgesundheitsministerium.de/)) with the participation of the ICD Working Group of the Board of Trustees for Questions of Classification in Health Care ([KKG](https://www.bfarm.de/DE/Kodiersysteme/Kooperationen-und-Projekte/KKG/_node.html))

**Comment by SimonCommits** [comment]
https://github.com/CHUV-DS/glowing-bear-medco-bioref/commit/3e01cb46039864f968ca1cc418ec534159b3844b
