### ISSUE TITLE
Creating predetermined cohort filters by enabling the tagging of default cohorts in the "saved cohorts" pane.

### ISSUE THREAD

**Issue by WiseIndian** [CHUV-DS/glowing-bear-medco-bioref#9]
> - As previously discussed, there needs to be preloaded (and “empty”) cohort criteria of AdministrativeSex, Age and other predetermined conditions for an easier UX. These concepts should be set to “any” or “all” by default. The user then only has to drag and drop the analyte (e.g. sodium) from the ontology for an analysis.

=> add predefined cohort filters in DB that are accessible to all users and cannot be deleted
=> enable the possibility of tagging one of the cohort filters as "default"
=> implement the logic to pre-fill the cohort definition panel with the default filter at login time

**Comment by JLRaisaro** [comment]
@nfreundl there is a bug when saving a cohort

**Comment by JLRaisaro** [comment]
the bug could not be reproduced
